name: flutter_application_3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_lints: ^4.0.0
  equatable: ^2.0.5
  formz: ^0.7.0
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  auth_repository:
    path: packages/auth_repository
  user_repository:
    path: packages/user_repository
  http: ^1.2.2
  english_words: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
